### ISSUE TITLE
`require': cannot load such file -- proxy-fetcher (LoadError)

### ISSUE THREAD

**Issue by radon1284** [nbulaj/proxy_fetcher#13]
```
ruby runner.rb                    
/Users/username/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- proxy-fetcher (LoadError)
	from /Users/username/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from runner.rb:6:in `<main>'
[~/Desktop]  $ 

```

the code im trying:
```
require 'proxy-fetcher'
manager = ProxyFetcher::Manager.new
manager.raw_proxies
```

**Comment by nbulaj** [comment]
@radon1284 wrong require statement. You need `require 'proxy_fetcher'` (underscore)
