### ISSUE TITLE
Integer bug?

### ISSUE THREAD

**Issue by khalilgharbaoui** [nbulaj/proxy_fetcher#16]
i'm just trying out your plugin... and this is what i get:

/usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/proxy_fetcher-0.6.3/lib/proxy_fetcher/providers/free_proxy_list.rb:28:in `Integer': invalid value for Integer(): "08080" (ArgumentError)
	from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/proxy_fetcher-0.6.3/lib/proxy_fetcher/providers/free_proxy_list.rb:28:in `block in to_proxy'
	from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/proxy_fetcher-0.6.3/lib/proxy_fetcher/providers/free_proxy_list.rb:26:in `tap'
	from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/proxy_fetcher-0.6.3/lib/proxy_fetcher/providers/free_proxy_list.rb:26:in `to_proxy'
	from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/proxy_fetcher-0.6.3/lib/proxy_fetcher/providers/base.rb:10:in `block in fetch_proxies!'
	from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/proxy_fetcher-0.6.3/lib/proxy_fetcher/providers/base.rb:10:in `map'
	from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/proxy_fetcher-0.6.3/lib/proxy_fetcher/providers/base.rb:10:in `fetch_proxies!'
	from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/proxy_fetcher-0.6.3/lib/proxy_fetcher/providers/base.rb:15:in `fetch_proxies!'
	from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/proxy_fetcher-0.6.3/lib/proxy_fetcher/manager.rb:38:in `block in refresh_list!'
	from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/proxy_fetcher-0.6.3/lib/proxy_fetcher/manager.rb:34:in `each'
	from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/proxy_fetcher-0.6.3/lib/proxy_fetcher/manager.rb:34:in `refresh_list!'
	from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/proxy_fetcher-0.6.3/lib/proxy_fetcher/manager.rb:19:in `initialize'
	from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/proxy_fetcher-0.6.3/bin/proxy_fetcher:60:in `new'
	from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/proxy_fetcher-0.6.3/bin/proxy_fetcher:60:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.3/bin/proxy_fetcher:22:in `load'
	from /usr/local/var/rbenv/versions/2.3.3/bin/proxy_fetcher:22:in `<main>'

**Comment by khalilgharbaoui** [comment]
solved by updating ruby i guess🤔
